/*
 * This source file was generated by the Gradle 'init' task
 */
package org.helmo.mma.admin.app;

import joptsimple.OptionParser;
import joptsimple.OptionSet;
import org.helmo.mma.admin.domains.core.BookingAggregator;
import org.helmo.mma.admin.domains.exceptions.DirException;
import org.helmo.mma.admin.infrastructures.*;
import org.helmo.mma.admin.presentations.MainPresenter;
import org.helmo.mma.admin.views.CLIView;

import java.io.IOException;
import java.sql.DriverManager;
import java.sql.SQLException;

public class Program {
    private static String path = "";

    public static void main(String[] args) throws DirException {
        if(!validGivenArgs(args)){
            throw new DirException("Valeur invalide ou manquante");
        }
        var connValues = path.split(";");
        var jdbc = String.format("jdbc:mysql://%s/Q210138?%s&%s",connValues[0],connValues[1],connValues[2]);
        BookingAggregator aggregator = null;

        try {
            var roomRepository = new RoomDbRepository(DriverManager.getConnection(jdbc));
            var userRepository = new UserDbRepository(DriverManager.getConnection(jdbc));
            var calendarRepository = new CalDbRepository(DriverManager.getConnection(jdbc));
            aggregator = new BookingAggregator(roomRepository, userRepository, calendarRepository);

        }catch (SQLException e){
            e.printStackTrace();
        }

        try(var view = new CLIView(System.in,System.out)){
            var mainPresenter = new MainPresenter(view,aggregator);
            view.run();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

    }

    /**
     * Vérifie si les arguments reçus sont valides
     * @param args
     * @return true si l'argument reçu est valide sinon false
     */
    private static boolean validGivenArgs(String[] args) {
        if(args.length < 1) {
            System.err.println("Argument requis db manquant ou incorrect");
            return false;
        }

        if(args.length > 1) {
            System.err.println("Trop arguments donné");
            return false;
        }

        var opts = parsingOpts(args);
        return opts.has("db");
    }

    private static OptionSet parsingOpts(String[] args) {
        OptionParser parser = new OptionParser();
        parser.accepts("db").withRequiredArg();
        var arg = args[0].split("=",2);
        var opts = parser.parse(arg);
        path = opts.valueOf("db").toString();
        return opts;
    }
}
